function [p, gof] = createFitSSP(depthlist, numdepths)
%CREATEFIT(DEPTHLIST,NUMDEPTHS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: depthlist
%      Y Output: numdepths
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Sep-2023 15:22:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( depthlist, numdepths );

% Set up fittype and options.
ft = 'linearinterp';
excludedPoints = (xData < 0) | (yData < 1400);
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';
opts.Exclude = excludedPoints;

% Fit model to data.
[p, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( p, xData, yData, excludedPoints );
legend( h, 'numdepths vs. depthlist', 'Excluded numdepths vs. depthlist', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'depthlist', 'Interpreter', 'none' );
ylabel( 'numdepths', 'Interpreter', 'none' );
grid on


